### ISSUE TITLE
Indentation suggestions

### ISSUE THREAD

**Issue by ml-2** [sogaiu/janet-ts-mode#2]
This is very nice! I will use it to edit janet from now on. I would like to suggest two things regarding indentation for now:

* I think cond should not be in janet-ts--indent-special-p, because that visually separates the first condition from its body.
* I would like to add a customizable variable janet-ts-indent-special-words to add extra custom values to indent-special. Mainly because I have been working on a DSL which includes a lot of defn-like macros which don't start with "def", and would like to be able to get good indentation for them without modifying janet-ts-mode directly.

I am willing to make a pull request for one or both of these changes if they are acceptable.

**Comment by sogaiu** [comment]
Thanks for taking a look and sharing your thoughts.

Regarding your first point, I'm not quite sure I follow, would you mind providing an example?

I have found [Janet's `cond`](https://github.com/janet-lang/spork/blob/a3ee63c137ee3234987dbbca71b566994ff8ae8c/spork/fmt.janet#L80-L88) to be a little different from "traditional" lisps (though perhaps it's similar to [what Clojure does](https://clojuredocs.org/clojure.core/cond)) and I've tried to emulate what I've seen in `spork/fmt` as well as `boot.janet`, but I'm not sure what I have in mind is the same as what you described.  Are you getting results that are different from something like [this](https://github.com/janet-lang/janet/blob/d9ed7a77f889f632ebbee1c111419170e201548c/src/boot/boot.janet#L2208-L2222)?

If you want to do something like (though without the extra parens):
```emacs-lisp
(cond ((numberp x) x)
      ((stringp x) x)
      ((bufferp x)
       (setq temporary-hack x) ; multiple body-forms
       (buffer-name x))        ; in one clause
      ((symbolp x) (symbol-value x)))
```

perhaps there's some way I can provide a way to customize things.

As to a customizable variable `janet-ts-indent-special-words`, that sounds reasonable.  

Would the addition of another form to `janet-ts--indent-special-p` like:

```emacs-lisp
(member head-text janet-ts-indent-special-words)
```

work for you?  If so, I'm happy to do that.  If there's a different way you think might be better I'm willing to consider -- as the code in its current state has mostly been about just getting things working :)

**Comment by sogaiu** [comment]
Thanks for the explanations.

Re: cond

I've tried out your suggestion for removing `cond` and so far it seems to work well.  I'll go ahead and make that change.

I agree that it didn't look good -- my work-around had been to change the way I wrote `cond`, but your idea seems to be working well so I'm happy to adopt that.

Re: janet-ts-indent-special-words

I'll use defcustom then, thanks for elaborating :)

If you notice anything off in the changes, please don't hestiate to let me know.

**Comment by sogaiu** [comment]
Ok, 175128f is intended to address `cond`'s indentation and 47c180c adds `janet-ts-indent-special-words` and hooks it up to `janet-ts--indent-special-p`.

Please let me know how they work for you.
