### ISSUE TITLE
treesit-inspect-mode enabled by default

### ISSUE THREAD

**Issue by alternateved** [sogaiu/janet-ts-mode#5]
Hello! 

Thanks a lot for that package (as well as every other part of Janet ecosystem of packages that you are maintaining). 

I have a small question in regards to `treesit-inspect-mode` - should this be enabled by default? It doesn't seem that helpful unless you are working on tree-sitter related things. I've also did not notice any other `*-ts-mode` packages doing that.

**Comment by sogaiu** [comment]
Thanks for the kind words and report :)

I agree that enabling `treesit-inspect-mode` by default doesn't make sense.  I've made an attempt to address that [here](https://github.com/sogaiu/janet-ts-mode/commit/6dcf4b695159a05568557ab0e089488bacfc5c63).

Please let me know if that works for you.

**Comment by alternateved** [comment]
This seems like a perfect solution! 

Thank you for taking into account my suggestion. Have a lovely day!
